<!doctype html>
<html lang="es">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="generator" content="Notepad++, Sublime Text 2" />
	<meta name="author" content="Rubén Martínez Vilar" />
	<meta name="keywords" content="Web, fotografía" />
	<meta name="description" content="Programación Hipermedia 2" />
	<title><?php echo $title; ?></title>

	<!-- Tipografias Google Web Fonts -->
	<link href='http://fonts.googleapis.com/css?family=Bitter:400,700' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>

	<!-- Estilos -->
	<link rel="stylesheet" type="text/css" href="css/resetCSS.css" media="screen" />
	<link rel="stylesheet/less" type="text/css" href="css/style-main.less" media="screen" />
	<link rel="stylesheet" type="text/css" href="css/style-print.css" media="print" />

	<!-- Scripts -->
	<!--[if lt IE 9]>
		<script src="js/html5shiv.js"></script>
		<script type="text/javascript" src="js/json2.js"></script>
	<![endif]-->
	<script type="text/javascript" src="js/less-1.3.3.min.js"></script>
	<script type="text/javascript" src="js/jquery-1.10.2.min.js"></script>
	<script type="text/javascript" src="js/jquery-migrate-1.2.1.min.js"></script>
	<script type="text/javascript" src="js/scripts-all.js"></script>
</head>
